<logs><log LogGUID="c5130c22-1169-463e-9255-c2c08922f304" LogFileID="" LogTypeKey="CACHE_REMOVED" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:48:54 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>DNN_GetLogTypeConfigInfoByKey</PropertyName><PropertyValue>Removed</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="86d2c7e6-aad2-496d-9697-7ab1faaf35f8" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:48:54 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>The AppDomain shut down because of a change to the application level configuration.</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="98f43fd4-3f49-49c9-b0e6-079eb9b037b6" LogFileID="" LogTypeKey="SCHEDULER_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:48:55 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>165dd68c-552c-4b48-93d1-e6579d7dc9e3</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>KRcKtVMx1NMq2GM7w14Esw==</ExceptionHash><Message>Thread was being aborted.</Message><StackTrace>   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(TimeSpan timeout)
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.Start()</StackTrace><InnerMessage /><InnerStackTrace /><Source>mscorlib</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="ca0743d8-05e1-483b-a066-aaac673a1f19" LogFileID="" LogTypeKey="CACHE_REMOVED" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:50:27 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>DNN_GetLogTypeConfigInfoByKey</PropertyName><PropertyValue>Removed</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="ed90d646-7b65-42f5-9e73-df91ff84b406" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:50:41 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>01f602e5-e621-4742-b012-fdd4b5e03813</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>dWCmGhO6LGJWuRQWhd2sUQ==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Host.ServerController.GetServersCallBack(CacheItemArgs cacheItemArgs)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage /><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="d01242e5-06dc-4f50-9b05-c9b1c414e434" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:50:41 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>The AppDomain shut down because of a change to the application level configuration.</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="46ed7b44-6581-4e03-9a49-98fcf96c11f5" LogFileID="" LogTypeKey="GENERAL_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:50:41 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>59a22e39-f0f4-45ee-b480-6df33951e993</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>1ofJuyKL/CJD6RzppEq/vg==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Entities.Host.ServerController.GetServersCallBack(CacheItemArgs cacheItemArgs)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)</StackTrace><InnerMessage /><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="39356c95-36e2-4ddc-9883-a25ca967dc34" LogFileID="" LogTypeKey="SCHEDULER_EXCEPTION" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:50:41 PM" LogCreateDateNum="0" BypassBuffering="False" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>AbsoluteURL</PropertyName><PropertyValue /></LogProperty><LogProperty><PropertyName>DefaultDataProvider</PropertyName><PropertyValue>DotNetNuke.Data.SqlDataProvider, DotNetNuke</PropertyValue></LogProperty><LogProperty><PropertyName>ExceptionGUID</PropertyName><PropertyValue>ffa5feef-d970-4606-a81c-c520bbee7804</PropertyValue></LogProperty></LogProperties><Exception><AssemblyVersion /><PortalId>0</PortalId><UserId>0</UserId><TabId>0</TabId><RawUrl /><Referrer /><UserAgent /><ExceptionHash>oPfsbhlx2XAi1PX/P8mWjg==</ExceptionHash><Message>A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)</Message><StackTrace>   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at PetaPoco.Database.OpenSharedConnection()
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, String sql, Object[] args)
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.LoadQueueFromTimer()
   at DotNetNuke.Services.Scheduling.Scheduler.CoreScheduler.Start()</StackTrace><InnerMessage /><InnerStackTrace /><Source>.Net SqlClient Data Provider</Source><FileName /><FileLineNumber>0</FileLineNumber><FileColumnNumber>0</FileColumnNumber><Method /></Exception></log>﻿<log LogGUID="d6c8425f-45f0-4653-89a8-1e43e72cc708" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:51:09 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>The AppDomain shut down because of a change to the application level configuration.</PropertyValue></LogProperty></LogProperties></log>﻿<log LogGUID="d27c07f8-bb0a-4b05-9692-c6a5fa998a34" LogFileID="" LogTypeKey="APPLICATION_SHUTTING_DOWN" LogUserID="-1" LogEventID="-1" LogUserName="" LogPortalID="-1" LogPortalName="" LogCreateDate="7/14/2015 4:58:11 PM" LogCreateDateNum="0" BypassBuffering="True" LogServerName="DEV-YASIR" LogConfigID=""><LogProperties><LogProperty><PropertyName>Shutdown Details</PropertyName><PropertyValue>The AppDomain shut down because of a change to the application level configuration.</PropertyValue></LogProperty></LogProperties></log></logs>
